version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - npm ci
  build:
    on-failure: ABORT
    commands:
      #- npm run lint
      #- npm run test:ci
      - npm run build
  post_build:
    commands:
      - aws s3 rm s3://art-therapy --recursive
artifacts:
  files:
    - '**/*'
  base-directory: dist/kreuzberg-kunsttherapie
